<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-house',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:51:34',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:52:13',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:42:58',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:43:01',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-07-05 11:02:08',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:42:51',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:52:13',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:52:13',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-03-16 18:52:13',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2023-03-16 18:13:54',
                'updated_at' => '2023-07-05 11:02:08',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2023-03-16 18:42:41',
                'updated_at' => '2023-07-05 11:02:08',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Limpiar Cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2023-03-16 18:47:14',
                'updated_at' => '2023-07-05 11:02:08',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Personas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2023-03-16 20:33:00',
                'updated_at' => '2023-03-16 22:07:55',
                'route' => 'voyager.people.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Categorias de Articulos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => 21,
                'order' => 4,
                'created_at' => '2023-03-16 23:46:13',
                'updated_at' => '2023-03-18 09:02:27',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Articulos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-tag',
                'color' => NULL,
                'parent_id' => 21,
                'order' => 3,
                'created_at' => '2023-03-17 04:40:55',
                'updated_at' => '2023-03-19 08:35:53',
                'route' => 'voyager.articles.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Almacen',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-store',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2023-03-17 04:58:11',
                'updated_at' => '2023-03-29 18:31:02',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Ingreso',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-sharp fa-solid fa-cart-shopping',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 1,
                'created_at' => '2023-03-17 05:13:08',
                'updated_at' => '2023-03-17 05:19:17',
                'route' => 'incomes.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Trabajadores',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person-digging',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2023-03-18 07:34:23',
                'updated_at' => '2023-03-29 18:31:02',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Personal',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person',
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 1,
                'created_at' => '2023-03-18 07:37:48',
                'updated_at' => '2023-03-18 07:37:53',
                'route' => 'worker.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Plantas de Hotel',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-puzzle-piece',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 3,
                'created_at' => '2023-03-18 08:04:50',
                'updated_at' => '2023-03-20 04:34:10',
                'route' => 'voyager.categories-facilities.index',
                'parameters' => 'null',
            ),
            20 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Estructura Hotel',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-hotel',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2023-03-18 08:08:32',
                'updated_at' => '2023-07-05 11:02:08',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Categorías',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 2,
                'created_at' => '2023-03-18 08:20:51',
                'updated_at' => '2023-03-21 16:45:49',
                'route' => 'voyager.categories-rooms.index',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Stock Disponible',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-brands fa-shopify',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 2,
                'created_at' => '2023-03-18 09:02:09',
                'updated_at' => '2023-03-19 08:35:53',
                'route' => 'income-article.stock',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Accesorio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-list',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 4,
                'created_at' => '2023-03-19 21:11:53',
                'updated_at' => '2023-03-21 16:46:22',
                'route' => 'voyager.parts-hotels.index',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Habitaciones',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-person-booth',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 1,
                'created_at' => '2023-03-20 04:33:57',
                'updated_at' => '2023-06-02 03:12:28',
                'route' => 'voyager.rooms.index',
                'parameters' => 'null',
            ),
            25 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Comidas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-bowl-food',
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 2,
                'created_at' => '2023-03-28 08:37:45',
                'updated_at' => '2023-03-28 08:52:33',
                'route' => 'voyager.food.index',
                'parameters' => 'null',
            ),
            26 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Comidas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-utensils',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2023-03-28 08:41:36',
                'updated_at' => '2023-03-29 18:31:02',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Menú del Día',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-list',
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 1,
                'created_at' => '2023-03-28 08:49:56',
                'updated_at' => '2023-03-28 08:52:32',
                'route' => 'voyager.food-menus.index',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Reportes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-chart-pie',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2023-03-29 17:56:15',
                'updated_at' => '2023-03-29 18:31:02',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Productos Vendidos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 35,
                'order' => 1,
                'created_at' => '2023-03-29 18:23:56',
                'updated_at' => '2023-03-30 00:13:53',
                'route' => 'report.saleproductserviceroom',
                'parameters' => 'null',
            ),
            30 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Ventas de Productos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-shopping',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2023-03-29 18:30:39',
                'updated_at' => '2023-03-29 18:31:02',
                'route' => 'sales.index',
                'parameters' => NULL,
            ),
            31 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Ventas De Comida',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 35,
                'order' => 2,
                'created_at' => '2023-03-30 00:40:10',
                'updated_at' => '2023-03-30 00:40:31',
                'route' => 'report.salefoodserviceroom',
                'parameters' => NULL,
            ),
            32 => 
            array (
                'id' => 39,
                'menu_id' => 1,
                'title' => 'Nacionalidades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-flag',
                'color' => '#000000',
                'parent_id' => 40,
                'order' => 1,
                'created_at' => '2023-06-19 09:26:35',
                'updated_at' => '2023-06-19 09:29:57',
                'route' => 'voyager.nationalities.index',
                'parameters' => 'null',
            ),
            33 => 
            array (
                'id' => 40,
                'menu_id' => 1,
                'title' => 'Parametros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2023-06-19 09:29:51',
                'updated_at' => '2023-07-05 11:02:08',
                'route' => NULL,
                'parameters' => '',
            ),
            34 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Paises',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-earth-americas',
                'color' => NULL,
                'parent_id' => 40,
                'order' => 2,
                'created_at' => '2023-06-20 06:18:39',
                'updated_at' => '2023-06-20 06:37:06',
                'route' => 'voyager.countries.index',
                'parameters' => NULL,
            ),
            35 => 
            array (
                'id' => 42,
                'menu_id' => 1,
                'title' => 'Departamentos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-milestone',
                'color' => NULL,
                'parent_id' => 40,
                'order' => 3,
                'created_at' => '2023-06-20 06:22:32',
                'updated_at' => '2023-06-20 06:37:15',
                'route' => 'voyager.departments.index',
                'parameters' => NULL,
            ),
            36 => 
            array (
                'id' => 43,
                'menu_id' => 1,
                'title' => 'Provincias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pie-graph',
                'color' => NULL,
                'parent_id' => 40,
                'order' => 4,
                'created_at' => '2023-06-20 06:29:03',
                'updated_at' => '2023-06-20 06:37:16',
                'route' => 'voyager.provinces.index',
                'parameters' => NULL,
            ),
            37 => 
            array (
                'id' => 44,
                'menu_id' => 1,
                'title' => 'Ciudades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-location',
                'color' => NULL,
                'parent_id' => 40,
                'order' => 5,
                'created_at' => '2023-06-20 06:33:33',
                'updated_at' => '2023-06-20 06:37:18',
                'route' => 'voyager.cities.index',
                'parameters' => NULL,
            ),
            38 => 
            array (
                'id' => 45,
                'menu_id' => 1,
                'title' => 'Productos de Limpieza',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-broom',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2023-07-05 10:56:10',
                'updated_at' => '2023-07-05 11:02:08',
                'route' => NULL,
                'parameters' => '',
            ),
            39 => 
            array (
                'id' => 46,
                'menu_id' => 1,
                'title' => 'Ingreso',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-cart-plus',
                'color' => '#000000',
                'parent_id' => 45,
                'order' => 1,
                'created_at' => '2023-07-05 11:01:01',
                'updated_at' => '2023-07-05 11:01:09',
                'route' => 'cleaningproducts.index',
                'parameters' => NULL,
            ),
            40 => 
            array (
                'id' => 47,
                'menu_id' => 1,
                'title' => 'Stock Disponible',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-brands fa-shopify',
                'color' => '#000000',
                'parent_id' => 45,
                'order' => 2,
                'created_at' => '2023-07-05 11:01:56',
                'updated_at' => '2023-07-05 11:02:00',
                'route' => NULL,
                'parameters' => NULL,
            ),
        ));
        
        
    }
}